### ISSUE TITLE
plugins always capitalizes characters with tone indicators (like é) and the character "ç", and capitalizes the next character

### ISSUE THREAD

**Issue by jack652** [Break-Ben/BetterDiscordAddons#5] opened 2022-09-02 19:27 UTC
plugins always capitalizes characters with tone indicators (like é) and the character "ç"
![image](https://user-images.githubusercontent.com/48365199/188223747-755b8968-fe1d-47b0-8d0f-40bcd82a7542.png)
![image](https://user-images.githubusercontent.com/48365199/188223752-2aea78a2-8587-4195-be26-ee3d0dbf4fd4.png)

in the first screenshot, the chatacter "A" after the "ç" isn't supposed to capitalized
and in the second screenshot, none of the characters were capitalized in the channel / chat name

it seems it also capitalizes the characters after tone indicators (like é) and the character "ç" are always capitalized, like if the plugin thought it was the beginning of the chat name

**Comment by Break-Ben** [comment] 2022-09-03 04:02
Duplicate of #2 _(and #3 and #4 lol)_, it is now fixed in 90cfd6a (1.3.4)

**Closed by Break-Ben** 2022-09-03 04:02 UTC
