### ISSUE TITLE
Accented characters are capitalized 

### ISSUE THREAD

**Issue by Lisandra-dev** [Break-Ben/BetterDiscordAddons#2] opened 2022-08-31 18:13 UTC
The plugin is great! But this bug annoys me as fuck xD

Every time an accented characters (ie `éèê`) appear : 
- The accented character is capitalized 
- The letter after the accented is also capitalized

See example : 
![image](https://user-images.githubusercontent.com/30244939/187749838-01881b53-e247-43d9-a7d8-e5db0243417c.png)
![image](https://user-images.githubusercontent.com/30244939/187749526-866abf87-c6e2-4f0c-908f-0ac63315d036.png)
![image](https://user-images.githubusercontent.com/30244939/187749554-42b587e3-179a-49fb-9ed4-53856fabaacc.png)

**Comment by szojusz** [comment] 2022-08-31 19:37
![image](https://user-images.githubusercontent.com/60299154/187767169-57bc51cf-3927-4d36-80cf-73e07c47a6da.png)
In Polish there is also such an error

**Comment by Break-Ben** [comment] 2022-09-01 10:17
Should be fixed in 90cfd6a (1.3.4), let me know if it still messes up in places
btw thanks lol

**Comment by Break-Ben** [comment] 2022-09-05 08:42
Reopening until the update is pushed on BD so people see this and stop reporting it as a new issue 
(to be clear, the issue is still fixed in 1.3.4+)

**Closed** 2022-09-06 23:50 UTC
