### ISSUE TITLE
[BetterChatNames] [Bug] Accent letters are detected as dashes.

### ISSUE THREAD

**Issue by Obazzi** [Break-Ben/BetterDiscordAddons#6] opened 2022-09-05 03:25 UTC
Accent letters are detected by the add-on as dashes, causing the accent letter and the letter next to it to get capitalized wrongly.
![image](https://user-images.githubusercontent.com/88412380/188354641-474f8d9a-5fdc-4bbc-ad60-0d853ec75135.png)
As you can see, it shows up as `FranÇAis` instead of `Français`.

I did not try this with other characters, so it might not just be an issues with accent letters.

**Comment by Break-Ben** [comment] 2022-09-05 08:15
Duplicate of #2, update to fix

**Closed by Break-Ben** 2022-09-05 08:15 UTC
